# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name=b'first_name'),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name=b'last_name'),
        ),
    ]
