# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 14:49
from __future__ import unicode_literals

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160303_1421'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userbase',
            managers=[
                ('objects', core.models.UserManagerWrapper()),
            ],
        ),
        migrations.AddField(
            model_name='userbase',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
