# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 23:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graciediet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGroupType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graciediet.TypeFood')),
            ],
        ),
        migrations.AlterField(
            model_name='food',
            name='type_food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graciediet.SubGroupType'),
        ),
    ]
