# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graciediet', '0003_auto_20160308_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graciediet.GroupFood')),
            ],
        ),
        migrations.RemoveField(
            model_name='food',
            name='type_food',
        ),
        migrations.DeleteModel(
            name='SubGroupType',
        ),
        migrations.AddField(
            model_name='food',
            name='sub_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='graciediet.SubGroup'),
        ),
    ]
