# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit_challenges', '0002_auto_20160303_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutrecipe',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
