# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit_challenges', '0003_workoutrecipe_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='quantity',
        ),
        migrations.AddField(
            model_name='workoutrecipe',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
