# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fit_challenges', '0004_auto_20160303_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('Seconds', 'Seconds'), ('Repeats', 'Repeat')], max_length=255),
        ),
    ]
