# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fit_challenges', '0005_auto_20160307_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fit_challenges/')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fit_challenges.Exercise')),
            ],
        ),
    ]
