# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fit_challenges', '0006_imageexercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='image',
        ),
        migrations.AlterField(
            model_name='imageexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagexercise', to='fit_challenges.Exercise'),
        ),
    ]
